.DATA
    IMAGE DQ ?
    SYSTEMTABLE DQ ?
    CONIN DQ ?
    CONOUT DQ ?
    WAITFORKEY DQ ?
    OUTPUTSTRING DQ ?
    BOOTSERVICES DQ ?
    WAITFOREVENT DQ ?
    INDEX DQ ?
    HELLOMESSAGE DW "H","I",","," ","T","H","E","R","E","!",10,13,0

.CODE
EFI_MAIN PROC
    MOV IMAGE, RCX
    MOV SYSTEMTABLE, RDX
    
    MOV RAX, QWORD PTR [RDX + 030H] ;SYSTEMTABLE->CONIN
        MOV CONIN, RAX
    MOV RBX, QWORD PTR [RAX + 10H] ;CONIN->WAITFORKEY
        MOV WAITFORKEY, RBX

    MOV RAX, QWORD PTR [RDX + 040H]
    MOV CONOUT, RAX
    MOV RBX, QWORD PTR [RAX + 08H]
    MOV OUTPUTSTRING, RBX

    MOV RAX, QWORD PTR [RDX + 60H] ;systemtable->bootservices
        MOV BOOTSERVICES, RAX
    MOV RBX, QWORD PTR [RAX + 60H] ; bootservices->waitforevent
        MOV WAITFOREVENT, RBX

    ;output to console
    MOV RCX, CONOUT
    LEA RDX, [HELLOMESSAGE]
    CALL OUTPUTSTRING

    ;WAIT FOR KEYBOARD INPUT
    MOV RCX, 01H
    LEA RDX, [CONIN]
    LEA R8, [INDEX]
    CALL WAITFOREVENT

    RET

EFI_MAIN ENDP

END